"""Mock Google Sheets data for spike testing.

Each fixture represents a sheet as a 2D list of cell values (like Sheets API returns).
These cover the 10 patterns identified in the spike plan.
"""


def clean_table():
    """Pattern 1: Clean table with headers + rows (sales data)."""
    return {
        "title": "Q1 Sales Report",
        "tabs": {
            "Sales": [
                ["Region", "Product", "Revenue", "Units"],
                ["North", "Widget A", "125000", "500"],
                ["South", "Widget A", "98000", "392"],
                ["North", "Widget B", "210000", "700"],
                ["South", "Widget B", "175000", "583"],
                ["East", "Widget A", "89000", "356"],
            ]
        },
    }


def multi_table():
    """Pattern 2: Two tables separated by blank rows on one sheet."""
    return {
        "title": "Sales & Inventory",
        "tabs": {
            "Data": [
                ["Monthly Sales", "", ""],
                ["Month", "Revenue", "Growth"],
                ["Jan", "500000", "5%"],
                ["Feb", "520000", "4%"],
                ["Mar", "550000", "6%"],
                ["", "", ""],
                ["", "", ""],
                ["Inventory Levels", "", ""],
                ["SKU", "Quantity", "Warehouse"],
                ["WA-001", "1200", "East"],
                ["WB-002", "800", "West"],
                ["WC-003", "350", "East"],
            ]
        },
    }


def notes_and_table():
    """Pattern 3: Free-text notes above a data table."""
    return {
        "title": "KPI Dashboard Notes",
        "tabs": {
            "Sheet1": [
                ["Q1 2025 Performance Summary"],
                ["Generated by the analytics team on Jan 15, 2025."],
                ["Note: All figures are in USD unless stated otherwise."],
                ["Contact: analytics@company.com for questions."],
                [""],
                ["Metric", "Target", "Actual", "Status"],
                ["DAU", "50000", "52300", "On Track"],
                ["Conversion Rate", "3.5%", "3.2%", "At Risk"],
                ["MRR", "$2M", "$2.1M", "On Track"],
                ["Churn", "2%", "1.8%", "On Track"],
            ]
        },
    }


def config_sheet():
    """Pattern 4: Key-value pairs (settings/thresholds)."""
    return {
        "title": "System Configuration",
        "tabs": {
            "Config": [
                ["Parameter", "Value"],
                ["max_retries", "3"],
                ["timeout_seconds", "30"],
                ["batch_size", "100"],
                ["log_level", "INFO"],
                ["enable_cache", "true"],
                ["cache_ttl_minutes", "15"],
                ["api_rate_limit", "1000/hour"],
            ]
        },
    }


def multi_tab():
    """Pattern 5: Multiple tabs — Summary, Raw Data, Config."""
    return {
        "title": "Monthly Report",
        "tabs": {
            "Summary": [
                ["Monthly Summary - March 2025"],
                [""],
                ["Metric", "Value"],
                ["Total Revenue", "$1.2M"],
                ["New Customers", "450"],
                ["Churn Rate", "1.5%"],
            ],
            "Raw Data": [
                ["Date", "Customer", "Amount", "Product"],
                ["2025-03-01", "Acme Corp", "15000", "Enterprise"],
                ["2025-03-01", "Beta Inc", "5000", "Pro"],
                ["2025-03-02", "Gamma LLC", "25000", "Enterprise"],
                ["2025-03-02", "Delta Co", "3000", "Starter"],
            ],
            "Config": [
                ["Setting", "Value"],
                ["report_period", "monthly"],
                ["currency", "USD"],
                ["include_churned", "false"],
            ],
        },
    }


def merged_cells():
    """Pattern 6: Header spanning multiple columns (simulated with repeated values)."""
    return {
        "title": "Department Budget",
        "tabs": {
            "Budget": [
                ["Department Budget 2025", "", "", "", ""],
                ["", "Q1", "Q1", "Q2", "Q2"],
                ["Department", "Budget", "Actual", "Budget", "Actual"],
                ["Engineering", "500000", "480000", "520000", ""],
                ["Marketing", "300000", "310000", "280000", ""],
                ["Sales", "200000", "195000", "210000", ""],
            ]
        },
    }


def mixed_content():
    """Pattern 7: Table + notes + config on same sheet."""
    return {
        "title": "Mixed Content Sheet",
        "tabs": {
            "Sheet1": [
                ["Project Status Report"],
                ["Last updated: 2025-03-15"],
                ["Owner: John Smith"],
                [""],
                ["Project", "Status", "Budget", "Deadline"],
                ["Alpha", "In Progress", "50000", "2025-06-01"],
                ["Beta", "Planning", "75000", "2025-09-01"],
                ["Gamma", "Complete", "30000", "2025-03-01"],
                [""],
                ["Notes:"],
                ["- Alpha is behind schedule by 2 weeks"],
                ["- Beta requires additional headcount"],
                [""],
                ["Settings", "Value"],
                ["review_frequency", "weekly"],
                ["escalation_threshold", "2 weeks"],
            ]
        },
    }


def sparse_data():
    """Pattern 8: Scattered data with many empty cells."""
    return {
        "title": "Sparse Sheet",
        "tabs": {
            "Sheet1": [
                ["", "", "Title", "", ""],
                ["", "", "", "", ""],
                ["", "Name", "", "Score", ""],
                ["", "Alice", "", "95", ""],
                ["", "", "", "", ""],
                ["", "Bob", "", "87", ""],
                ["", "", "", "", ""],
                ["", "Charlie", "", "92", ""],
            ]
        },
    }


def formulas_sheet():
    """Pattern 9: Columns with computed values (values shown, not formulas)."""
    return {
        "title": "Revenue Calculations",
        "tabs": {
            "Revenue": [
                ["Product", "Price", "Quantity", "Subtotal", "Tax", "Total"],
                ["Widget A", "25.00", "100", "2500.00", "250.00", "2750.00"],
                ["Widget B", "50.00", "75", "3750.00", "375.00", "4125.00"],
                ["Widget C", "10.00", "500", "5000.00", "500.00", "5500.00"],
                ["", "", "", "", "", ""],
                ["", "", "Grand Total:", "11250.00", "1125.00", "12375.00"],
            ]
        },
    }


def edge_cases():
    """Pattern 10: Edge cases — single row, single column, empty sheet."""
    return {
        "title": "Edge Cases",
        "tabs": {
            "Single Row": [
                ["Only", "One", "Row"],
            ],
            "Single Column": [
                ["Header"],
                ["Value1"],
                ["Value2"],
                ["Value3"],
            ],
            "Empty": [],
        },
    }


ALL_FIXTURES = {
    "clean_table": clean_table,
    "multi_table": multi_table,
    "notes_and_table": notes_and_table,
    "config_sheet": config_sheet,
    "multi_tab": multi_tab,
    "merged_cells": merged_cells,
    "mixed_content": mixed_content,
    "sparse_data": sparse_data,
    "formulas_sheet": formulas_sheet,
    "edge_cases": edge_cases,
}
